name: Light Town API

on:
  push:
    branches:
      - master
      - develop

env:
  PORT: ${{secrets.PORT}}
  TYPEORM_PORT: ${{secrets.TYPEORM_PORT}}
  TYPEORM_USERNAME: ${{secrets.TYPEORM_USERNAME}}
  TYPEORM_PASSWORD: ${{secrets.TYPEORM_PASSWORD}}
  TYPEORM_DATABASE: ${{secrets.TYPEORM_DATABASE}}
  JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
  TYPEORM_CONNECTION: ${{secrets.TYPEORM_CONNECTION}}
  TYPEORM_SYNCHRONIZE: ${{secrets.TYPEORM_SYNCHRONIZE}}
  TYPEORM_ENTITIES: ${{secrets.TYPEORM_ENTITIES}}
  NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run Docker Compose
        run: docker-compose --file docker-compose.test.yml up --build --abort-on-container-exit
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
